// Autogenerated by RTK


export async function get_user(id: number, ): Promise<{ id: number, username: string }> {
	return fetch("/user/{id}", {
		method: "GET",
		headers: json ? {
			"Content-Type": "application/json",
		} : {},
		body: json && JSON.stringify(json),
	});
}

export async function add_user(json: { username: string }, ): Promise<{ id: number, username: string }> {
	return fetch("/user", {
		method: "POST",
		headers: json ? {
			"Content-Type": "application/json",
		} : {},
		body: json && JSON.stringify(json),
	});
}
